FROM node:22-bookworm-slim
WORKDIR /app

COPY package.json ./
COPY apps/api/package.json ./apps/api/package.json
COPY apps/media/package.json ./apps/media/package.json
COPY apps/web/package.json ./apps/web/package.json
RUN npm install

COPY . .
WORKDIR /app/apps/web
CMD ["npm", "run", "dev"]
