FROM node:22-bookworm-slim
WORKDIR /app

COPY package.json ./
COPY apps/api/package.json ./apps/api/package.json
COPY apps/media/package.json ./apps/media/package.json
COPY apps/web/package.json ./apps/web/package.json
RUN npm install

COPY . .
RUN npx prisma generate --schema=/app/prisma/schema.postgres.prisma

WORKDIR /app/apps/api
CMD ["sh", "-c", "npx prisma db push --schema=/app/prisma/schema.postgres.prisma && npm run dev"]
